### PR TITLE
Package level manpage

### PR DESCRIPTION
**Pull request by kakopo**
Added a package level man page.

### CODE REVIEW

**Comment by hpages** [comment]
Hi @kakopo,

PR looks good. Some minor cosmetic things about the package-level man page:

- Common usage is to put an hyphen between the name of the package and `package` in `\name{BSgenomeForgepackage}` and `\alias{BSgenomeForgepackage}`. You can also add an additional alias that is just the package name if that alias is not already used in another man page. So:
    ```
    \name{BSgenomeForge-package}
    
    \alias{BSgenomeForge-package}
    \alias{BSgenomeForge}
    
    \title{The BSgenomeForge package}
    ...
    ```
  Also note the title "The BSgenomeForge package" instead of just "BSgenomeForge".

- Use `\pkg{}` instead of `\code{}` for package names.  Also I would just use "provides" instead of "is comprised of" (boring, I know :wink: ):
    ```
    \details{
    \pkg{BSgenomeForge} is comprised of two major functions, etc...
    ...
    }
    ```

- Finally please indent the content of the `\description`, `\details`, and `\author` sections with 2 spaces.

Thanks,
H.

**Comment by kakopo** [comment]
Hi @hpages. Thank you for the feedback. I've worked on the necessary changes described, and hope the man page is much better now!

**Comment by hpages** [comment]
Thanks. Note that only the _content_ of the `\description`, `\details`, and `\author` sections need to be indented, just the same way you did it in the other man pages that you wrote. See for example `man/forgeBSgenomeDataPkgFromNCBI.Rd`.

Also please rename the file `BSgenomeForgepackage.Rd` -> `BSgenomeForge-package.Rd`.

Thanks again!

**Comment by kakopo** [comment]
Sorry about that! I've just updated the file. Thank you for the feedback, as always :relaxed:.

**Comment by hpages** [comment]
Looks like you forgot to remove `man/BSgenomeForgepackage.Rd`?

FWIW I usually rename a file that is already in git with `git mv`:
```
git mv oldname newname
```
If the file is not already in git, it's just `mv oldname newname`.

Thanks!

**Comment by kakopo** [comment]
`mv oldname newname`  will definitely be handy, thank you. I'd removed the original file locally but didn't know it still existed! I've deleted the old file.

**Comment by hpages** [comment]
Thanks. `mv oldname newname` will only rename the file locally but not in git. You need to do `git mv oldname newname` for that.

**Pull request merged**
