### PR TITLE
Add 'assembly_accession' argument to fastaTo2bit()

### PR DESCRIPTION
**Pull request by kakopo**

### CODE REVIEW

**Comment by hpages** [comment]
Thanks @kakopo for the PR.

Note that I get these warnings when I install the package:
```
hpages@spectre:~/github/kakopo$ bdevinst BSgenomeForge_0.0.3.tar.gz 
* installing to library ‘/home/hpages/R/R-4.3.r83438/library’
* installing *source* package ‘BSgenomeForge’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
Warning: fastaTo2bit.Rd:77: unexpected '}'
Warning: fastaTo2bit.Rd:75: All text must be in a section
Warning: fastaTo2bit.Rd:76: All text must be in a section
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (BSgenomeForge)
```
and also when I run `R CMD check` on it:
```
hpages@spectre:~/github/kakopo$ bdevcheck BSgenomeForge_0.0.3.tar.gz
* using log directory ‘/home/hpages/github/kakopo/BSgenomeForge.Rcheck’
* using R Under development (unstable) (2022-12-12 r83438)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘BSgenomeForge/DESCRIPTION’ ... OK
* this is package ‘BSgenomeForge’ version ‘0.0.3’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... NOTE
Depends: includes the non-default packages:
  'BiocGenerics', 'S4Vectors', 'IRanges', 'GenomeInfoDb', 'Biostrings',
  'BSgenome'
Adding so many packages to the search path is excessive and importing
selectively is preferable.
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘BSgenomeForge’ can be installed ... WARNING
Found the following significant warnings:
  Warning: fastaTo2bit.Rd:77: unexpected '}'
  Warning: fastaTo2bit.Rd:75: All text must be in a section
  Warning: fastaTo2bit.Rd:76: All text must be in a section
See ‘/home/hpages/github/kakopo/BSgenomeForge.Rcheck/00install.out’ for details.
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... WARNING
prepare_Rd: fastaTo2bit.Rd:77: unexpected '}'
prepare_Rd: fastaTo2bit.Rd:75: All text must be in a section
prepare_Rd: fastaTo2bit.Rd:76: All text must be in a section
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking PDF version of manual ... OK
* DONE

Status: 2 WARNINGs, 1 NOTE
See
  ‘/home/hpages/github/kakopo/BSgenomeForge.Rcheck/00check.log’
for details.
```
Please address.

Keep in mind that the `assembly_accession` argument is _optional_, that is, the function should still work when called without this argument. Look at the **Typical use** I showed in issue #7. Can you run that code?

The documentation of the `assembly_accession` argument should clarify that the argument is optional and explain what happens when it's supplied.

Not all NCBI assemblies have a GenBank and a RefSeq accession. Sometimes they only have one. So the user should be able to use one or the other. Does the code I showed in **Typical use** work if we replace the RefSeq number (`GCF_009729545.1`) with the corresponding GenBank number (`GCA_009729545.1`)? 

Let's provide 2 examples, one for a RefSeq assembly accession like you did, and one with a GenBank assembly accession. We should also consider showing the user what happens when they don't specify the `assembly_accession` argument, so they understand what the problem is and they can see how specifying `assembly_accession` solves it.

Here is what the examples section could look like (I'm putting the GenBank example first):
```
\examples{
## Most assemblies at NCBI can be accessed using either their GenBank or
## RefSeq assembly accession. For example assembly ASM972954v1 (for
## Acidianus infernus) can be accessed either with GCA_009729545.1 (GenBank
## assembly accession) or GCF_009729545.1 (RefSeq assembly accession).
## See https://www.ncbi.nlm.nih.gov/assembly/GCA_009729545.1
## or https://www.ncbi.nlm.nih.gov/assembly/GCF_009729545.1 for
## the landing page of this assembly.

## ---------------------------------------------------------------------
## USING FASTA FILE FROM **GenBank** ASSEMBLY
## ---------------------------------------------------------------------

## Download the FASTA file containing the genomic sequences for
## the ASM972954v1 assembly to the tempdir() folder:
fasta_path <- downloadGenomicSequencesFromNCBI("GCA_009729545.1",
                                               destdir=tempdir())

## Use fastaTo2bit() to convert the file to 2bit. We're using the function
## in its simplest form here so there won't be any sequence renaming
## or reordering:
twobitpath1 <- tempfile(fileext=".2bit")
fastaTo2bit(fasta_path, twobitpath1)

## Take a look at the sequence names in the resulting 2bit file:
names(import.2bit(twobitpath1)

## Use fastaTo2bit() again to convert the file to 2bit. This time we want
## the function to rename and reorder the sequences as in
## getChromInfoFromNCBI("GCA_009729545.1"), so we supply "GCA_009729545.1":
twobitpath2 <- tempfile(fileext=".2bit")
fastaTo2bit(fasta_path, twobitpath2, assembly_accession="GCA_009729545.1")

## Take a look at the sequence names in the resulting 2bit file:
names(import.2bit(twobitpath2))

## ---------------------------------------------------------------------
## USING FASTA FILE FROM **RefSeq** ASSEMBLY
## ---------------------------------------------------------------------

(same as above but using GCF_009729545.1 instead of GCA_009729545.1)
...
...
}
```
Note that using `tempfile()` is another convenient way to obtained the path to a temporary file. The function only produces the path but it doesn't create the file. See `?tempfile`.

Let me know if you have questions about this.

H.

**Comment by hpages** [comment]
Thanks @kakopo.

Please indent your `if (!is.na(assembly_accession)) ` statement properly.

2 suggestions:

- I'd suggest that you check the `assembly_accession` argument with `isSingleStringOrNA()` as part of the argument checking. You want to do this before the `if (!is.na(assembly_accession))` statement.

- You could also factor out the code in the `if` statement and put it in its own helper function. This would look like this:

```
.sort_and_rename <- function(dna, assembly_accession)
{
    ...
}

fastaTo2bit <- function(origfile, destfile, assembly_accession=NA)
{
    ...
    ...

    dna <- readDNAStringSet(origfile)

    if (!is.na(assembly_accession))
        dna <- .sort_and_rename(dna, assembly_accession)

    ### Export file as 2bit
    export.2bit (dna, destfile)
}
```
The dot prefix in `.sort_and_rename` is just a naming convention for non-exported helper functions.

Also please see my previous feedback about the install warnings, the documentation of the `assembly_accession` argument, using a GenBank assembly accession instead of a RefSeq one, etc... Make sure to let me know if you have questions or need further explanations.

Thanks

**Comment by kakopo** [comment]
Hi @hpages. I've pushed the edited code that I am working on, however, the fastaTo2bit function does not work as expected if the assembly_accession argument is specified. I'd appreciate a few pointers on what may be missing.
Because of this, the examples under the man page may not work- I comment them out before running R CMD check.

**Comment by kakopo** [comment]
I have updated the code and man pages, and all seems to work well! Kindly take a look at the PR. I hope it is satisfactory.

**Comment by hpages** [comment]
Alright.
- Make sure to indent your `if` statements properly.
- Don't forget to check the `assembly_accession` argument.
- You're using the RefSeq accession in the USING FASTA FILE FROM **GenBank** ASSEMBLY example, and the GenBank accession in the USING FASTA FILE FROM **RefSeq** ASSEMBLY example. Should be the otherway around.

Please commit and push. I'll have a couple more things to add later. Thanks!

**Comment by kakopo** [comment]
Hi @hpages. I've implemented the stated changes. I hope the PR is satisfactory. Looking forward to the next task.

**Comment by kakopo** [comment]
Hi @hpages. Thank you for the advice plus the corrections. I've implemented everything mentioned. Hope the latest commit is well!

**Pull request merged**
