### PR TITLE
Implement, export, and document forgeBSgenomeDataPkgFromNCBI()

### PR DESCRIPTION
**Pull request by kakopo**

### CODE REVIEW

**Comment by kakopo** [comment]
Hi @hpages. Thank you so much for the help shared today.  I have added the missing functionality and tried to carry out a few tests, and everything seems to work as expected, although I suspect the missing circular checks is the reason why `identical(seqinfo(Ainfernus), getChromInfoFromNCBI("ASM972954v1", as.Seqinfo=TRUE))` returns a `FALSE` value. 
Please take a look at the most recent code pushed. Thank you!

**Comment by hpages** [comment]
You have a working version of the function! :tada: :partying_face: This is a great milestone!

> I suspect the missing circular checks is the reason why `identical(seqinfo(Ainfernus), getChromInfoFromNCBI("ASM972954v1", as.Seqinfo=TRUE))` returns a FALSE value.

Exactly! You can actually spot the difference with your own eyes:
```
> seqinfo(Ainfernus)
Seqinfo object with 4 sequences from ASM972954v1 genome:
  seqnames seqlengths isCircular      genome
  contig_1    2186600      FALSE ASM972954v1
  contig_2      16994      FALSE ASM972954v1
  contig_3       3763      FALSE ASM972954v1
  contig_4      15057      FALSE ASM972954v1
```
No circular sequence! (which is as expected because we've set `CIRCSEQS` to `character(0)` for now.

```
# I guess you meant to use "GCA_009729545.1" instead of "ASM972954v1" here (the latter
# doesn't work because this assembly is not registered in GenomeInfoDb).

> getChromInfoFromNCBI("GCA_009729545.1", as.Seqinfo=TRUE)
Seqinfo object with 4 sequences from GCA_009729545.1 genome:
  seqnames seqlengths isCircular          genome
  contig_1    2186600         NA GCA_009729545.1
  contig_2      16994         NA GCA_009729545.1
  contig_3       3763         NA GCA_009729545.1
  contig_4      15057         NA GCA_009729545.1
```

The circularity flags are set to NA. This is expected because, again, this assembly is not registered in **GenomeInfoDb**.

We'll deal with the circularity flag issue in a separate issue.

Other than that, there are some minor issues with your code that we can discuss during our next call.

One thing that I suggest you start doing is reorganize your code to handle small tasks in separate helper functions e.g. one for abbreviating the organism name (`BSGENOMEOBJNAME`), one for constructing the 4th part of the package name by removing problematic characters from `genome`, and so on.

Even for tasks as simple as producing the values of the `PKGTITLE` and `PKGDESCRIPTION` symbols, it's worth using helper functions. This will makes the code easier to read, understand, and maintain. It will also make it easier to test each helper function individually, and make sure that they do the right thing. For example, if you have a helper function for constructing the 4th part of the package name, say `.make_pkgname_part4()`, you'll be able to test it directly on many different `genome` values that you make up, and see what it does. This is going to be a lot more convenient than calling the big and slow `forgeBSgenomeDataPkgFromNCBI()` function on many different `genome` values to see how it goes (the function needs to download a big FASTA file each time we call it :face_with_head_bandage:).

H.

**Comment by kakopo** [comment]
Thank you!
I've incorporated the changes we discussed over the call. The pointers were very helpful. Hopefully the latest commit is much neater. It is certainly much easier to debug!

**Comment by hpages** [comment]
The changes look good, thanks. And yes, the code is much neater and easier to read.

A few things:

- We should always avoid to use `/` explicitely when we form a path to a local file or directory. Good practice is to always use `file.path()` (or `system.file()`) to put together _all_ the components of a path. So for example, instead of `file.path(file_dir, "inst/extdata")`, we should do `file.path(file_dir, "inst", "extdata")`.

- As discussed last Friday, let's _move_ `single_sequences.2bit` rather than copy it. Moving is much more efficient than copying and it saves disk space. Since we don't need to keep the original `single_sequences.2bit` anyway, there's no reason to copy the file.

- Good job with your `.abbreviate_pkgname()` helper. It does the right thing with full organism names that have more than 2 parts e.g. with `Canis lupus familiaris` it produces:
    ```
    > .abbreviate_pkgname("Canis lupus familiaris")
    [1] "Cfamiliaris"
    ```
    This is good because the "binomial name" for Dog is "Canis familiaris" (see https://en.wikipedia.org/wiki/Dog). Also this is consistent with what was done so far for other BSgenome data packages for Dog. See https://bioconductor.org/packages/release/BiocViews.html#___Canis_familiaris

- I personally find the name of the `.abbreviate_pkgname()` helper a little bit misleading. The function abbreviates the _organism name_, not the _package name_. Yes, the abbreviated organism name is going to be used as part 2 of the package name, but it's better to name functions based on what they do rather than on how/where the value they return is going to be used.
 
- Does `.create_org_score()` do the right thing on `Canis lupus familiaris`?

- This looks more complicated than it needs to be:
    ```
    .make_pkgname_part4 <- function(genome)
    {
        if (grepl("[^0-9a-zA-Z.]", genome)) {
            genome_name <- gsub("[^0-9a-zA-Z.]", "", genome)
        } else {
            genome_name <- genome
        }
        genome_name
    }
    ```
    How about this:
    ```
     .make_pkgname_part4 <- function(genome)
    {
        forbidden_letter <- "[^0-9a-zA-Z.]"
        if (!grepl(forbidden_letter, genome))
            return(genome)
        gsub(forbidden_letter, "", genome)
    }
    ```
    or just:
    ```
     .make_pkgname_part4 <- function(genome) gsub("[^0-9a-zA-Z.]", "", genome)
    ```
    Note that this formatting is ok in this case because the body of the function is made of a single call so there's no need to use `{` and `}`, and also the line is less than 80 characters.

- Please also consider adding argument checks for those arguments that are not checked yet e.g. `pkg_maintainer`, `pkg_author`, etc...

- What happens if the user supplies an empty string for `organism` or for `genome`?

- The most important part of `pkg_maintainer` is the email address of the maintainer (having the name of the maintainer is nice but not as important). So the function should fail (with an informative error message) if the user supplies `"Jane Doe"` instead of `"Jane Doe <janedoe@gmail.com>"`. More generally speaking, it would be nice to add a quick check that `pkg_maintainer` looks as expected, i.e. is of the form `"Jane Doe <janedoe@gmail.com>"` or `janedoe@gmail.com`.

- Your code assumes that the user will supply `organism` with the right capitalization but we know that users are not always very cautious e.g. it's easy to imagine that some would supply things like `homo sapiens` or `Homo Sapiens`. Note that things like this would cause problems. Of course there's always ways for users to misuse things and most of the time we can't do much about it (except that we should always try to fail as gracefully as possible). But in this case, it seems easy enough to adapt our code to make it work even if capitalization is incorrect.

- If you look closely at the value returned by `createPackage()`, it's kind of more complicated than just a single string containing the path to the package. It's actually a _named list_ containing a single element, and this single element is the path to the package. In other words, the string containing the path is wrapped inside a length-one list. This is a really strange decision by the authors of `createPackage()` but that's how it is.
    The problem is that your code doesn't seem to acknowledge that i.e. it stores the value returned by `createPackage()` in a variable named `file_dir` (which BTW is not a very good name for this variable), and then `file_dir` gets passed _as-is_ to `file.copy()`, and this just works! However I think this works only by chance, because, if you look at the documentation for `file.copy()`, the `from` and `to` arguments are expected to be character vectors, not lists. The fact that `file.copy()` also accepts a list for `from` is an undocumented feature, so we should not rely on it.
    So let's make sure that we pass strings (i.e. character vectors of length 1) to `file.copy()` (or `file.rename()`).

- About the value returned by the `forgeBSgenomeDataPkgFromNCBI()` function. The man page says:
    ```
    \value{
      A logical TRUE if the package is created, a logical FALSE if it is not.
    }
    ```
    I think it would be more useful to have the function return the path to the forged package. If for whatever reason the function fails to create the package, then it will raise an error before it can complete, so it won't actually return a value. The function should also raise an error if the final step (move `single_sequences.2bit` to the package folder) fails. In other words, if the function is actually able to complete and return a value, that means that the package was sucessfully forged and has the `single_sequences.2bit` file in it. So returning a `TRUE` in that case is not really adding anything. Returning the path to the forged package sounds more useful (e.g. this path could be used to programatically run `R CMD build` on the package).

Let me know if you have questions.

Thanks

**Comment by hpages** [comment]
Two more things:

- The abbreviated organism name (e.g. Cfamiliaris) is computed twice when it only needs to be computed once. We should always try to avoid computing the same thing twice, even if the cost of computing that thing is small. In this case it's very easy to do: just pass `abbr_name` instead of `organism` to the call to `.create_pkgname()`, remove the `abbr_name <- .abbreviate_pkgname(organism)` line in the body of the `.create_pkgname()` function, and rename its first argument `abbr_name`.

- `abbr_name` is not a great name for this variable or argument. I suggest that you use something a little bit more specific like `abbr_organism`. You could also rename the `.abbreviate_pkgname()` helper -> `.abbreviate_organism()` or `.get_abbr_organism()` for more consistent naming overall.

Thanks

**Comment by hpages** [comment]
Note that `isSingleString()` already checks that its argument is not NA so there's no need to explicitely check that again.

The `.check_organism_case()` approach works and is already an improvement to the previous situation. Have you considered _fixing_ the case of the supplied `organism` instead of raising an error if the case is not as expected? It doesn't involve much more code than what you're doing but it would be a more user-friendly solution.

Could just be something like this:
```
.format_organism <- function(organism)
{
    first_letter <- substring(organism, 1, 1)
    other_letters <- substring(organism, 2)
    paste0(toupper(first_letter), tolower(other_letters))
}
```
The call it early in the body of `forgeBSgenomeDataPkgFromNCBI` to fix `organism` once for all.

The additional checks you do on `pkg_maintainer` should go in an helper function e.g.  `.check_pkg_maintainer()` (similarly to what you did with `.check_organism_case()`). Note that you cannot assume that everybody has an email address that ends up with `.com`. A lot of people don't (look at Nikos or Vince addresses for example).

**Comment by kakopo** [comment]
Hi Hervé! 
Thank you for the feedback. I hadn't considered alternate email addresses :sweat_smile:, but now I have worked on that, in addition to the suggested changes. Please take a look at the most recent commits. Thank you.

**Comment by hpages** [comment]
Thanks! More feedback:

- Instead of having:
    ``` 
    if (!isSingleString(organism))
         stop(wmsg("'organism' must be a single string"))
    ...
    ```
    and a few lines later
    ```
    ...
     if (organism == '')
         stop(wmsg("'organism' must be a valid string value"))
    ```
    how about having:
    ```
    if (!isSingleString(organism) || organism == "")
        stop(wmsg("'organism' must be a single (non-empty) string"))
    ```

- Still no argument check for `pkg_author`, `pkg_version`, or `license`?

- You're already computing the path to the 2bit file, and storing it in the `twobitfile` variable. So `.move_seq_file()` shouldn't have to do it again. The problem with having this path computed twice, in two separate functions, both using exactly the same expression (`file.path(tempdir(), "single_sequences.2bit")`), is the following: if for whatever reason this path needs to be modified in the future, then the two expressions will need to be modified to remain in agreement. There's a general principle in software engeneering called the DRY principle (Don't Repeat Yourself). In this particular situation, the repetition can easily be avoided by passing `twobitfile` to the `.move_seq_file()` function (this requires that you add another argument to the function, e.g. `twobitfile`). Furthermore, `.move_seq_file()` can then call `basename()` on `twobitfile` to extract the name of the 2bit file (`single_sequences.2bit`) so you don't need to hardcode the name of the file again here.

**Various problems with `.check_organism_spaces()`**

    .check_organism_spaces <- function(organism)
    {
        organism <- gsub("(?<=[\\s])\\s*|^\\s+|\\s+$", "", organism, perl = TRUE)
        organism
    }

- First, you're not using the function anywhere.

- Also it's hard to know what this function does. The name suggests that it checks the spaces in `organism`, but what does it do exactly with them? Whoever is going to maintain this code in the future will need to decipher the complicated regular expression in order to find out what the intention behind the code is. This is not going to be fun, and they might not be able to come to the right conclusion. We have 3 ways to improve the situation: (1) use a more descriptive function name, (2) put a comment that explains what the code does, (3) simplify your code.

- Here I'm simplifying the code _and_ using comments:
    ```
    ## Remove leading and trailing whitespaces (like strip() in Python):
    organism <- gsub("^\\s*|\\s*$", "", organism)
    ## Replace multiple whitespaces with single space:
    organism <- gsub("\\s+", " ", organism)
    ```

- Finally note that what you are doing here in `.check_organism_spaces()` is also part of the process of putting `organism` in the correct/standard form, so it would make sense to have `.format_organism()` take care of that.

**About `.check_pkg_maintainer()`**

    .check_pkg_maintainer <- function(pkg_maintainer)
    {
        if(grepl("\\<[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\>", as.character(pkg_maintainer), ignore.case=TRUE) == TRUE){
            return(pkg_maintainer)
        }else{
            stop(wmsg("Please enter a valid email address"))
        }
    }

- Same issues as with `.check_organism_spaces()`. Regular expressions are powerful! However, using long and complicated regular expressions tends to make our code hard to understand and to maintain. We can mitigate this by trying to simplify them as much as possible, and by using comments.

- Why pass `pkg_maintainer` thru `as.character()`? Because to the argument checking performed earlier in `forgeBSgenomeDataPkgFromNCBI()`, don't we have the guarantee that `pkg_maintainer` is already a character vector of length 1?

- Note that doing something like `if (foo(...) == TRUE) ...` is not considered good coding style. Just do `if (foo(...)) ...` instead.

- We usually put spaces in `if` statements i.e. instead of:
    ```
        if(...){
            ...
        }else{
            ...
        }
    ```
    we do:
    ```
        if (...) {
            ...
        } else {
            ...
        }
    ```

- Note that you don't even need an `if else` statement here, an `if` statement is enough:
    ```
    .check_pkg_maintainer <- function(pkg_maintainer)
    {
        pattern <- "\\<[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\>"
        if (grepl(pattern, pkg_maintainer, ignore.case=TRUE))
            return(pkg_maintainer)
        stop(wmsg("Please enter a valid email address"))
    }
    ```

**Comment by kakopo** [comment]
Hi @hpages , thank you for the feedback! I apologise for the oversights in the function checks - I have worked on them. I also added the `circ_seqs` argument but have not yet updated the documentation, shall push the updated code and man page afterwards.

**Comment by hpages** [comment]
Thanks again for all the corrections and improvements.

Still a few minor things though... but we're almost there!

- About `.move_seq_file()`:

  - What about using `basename()` to extract the name of the 2bit file as suggested earlier? (see my previous comment above about this). Hardcoding the exact name of the 2bit file inside the function introduces a repetition: this name is already hardcoded in the body of the `forgeBSgenomeDataPkgFromNCBI` function. So the same knowledge is coded in two different places. This means that, if for whatever reason this name needs to be changed in the future, then it will need to be changed in two places. Not ideal! (This is the DRY principle again.)
  This can easily be avoided by using `basename()` to make `.move_seq_file()` _agnostic_ about the exact name of the file to move.
 
  - The function has its arguments in a very counter-intuitive order. This is very likely to confuse and mislead whoever will try to understand and/or maintain your code.

- Let's have `forgeBSgenomeDataPkgFromNCBI()` return the path to the created package as an invisible string. The man page should mention that too (see for example the man pages for `downloadGenomicSequencesFromNCBI()` or `downloadGenomicSequencesFromUCSC()`).

Man page:

- In `\title`, `\description`, `\item{pkg_version}`, and `\examples`: It should be BSgenome _data_ package. This is to avoid any potential confusion with the BSgenome package, which is a software package.
  Also let's use "create" instead of "make". 

- In `\description`: Maybe slightly rephrase:
    ```
    The \code{forgeBSgenomeDataPkgFRomNCBI} function allows the user to create a
    BSgenome data package from an NCBI assembly.
    ```
- Wrap strings like `"Homo sapiens"`, `"felCat9.1_X"`, etc... in `\code{}`.

- In `\item{pkg_maintainer}`: Put `Jane Doe, <janedoe@gmail.com>` between double quotes (`"`) to show an R string, and wrap that in `\code{}`.

- In `\item{pkg_author}`: Should be "this takes the value of pkg_maintainer" instead of "this takes the value of pkg_author". Also let's wrap pkg_maintainer in `\code{}`.

- Instead of:
    ```
    \item The \code{\link{downloadGenomicSequencesFromNCBI}} function that
          downloads genomic sequences from NCBI.
    
    \item The \code{\link{fastaTo2bit}} function that converts a FASTA file
          to the 2bit format.
    ```
  let's provide a little bit more details:
    ```
    \item The \code{\link{downloadGenomicSequencesFromNCBI}} function that
          \code{forgeBSgenomeDataPkgFromNCBI} uses internally to download
          the genomic sequences from NCBI.
    
    \item The \code{\link{fastaTo2bit}} function that
          \code{forgeBSgenomeDataPkgFromNCBI} uses internally to convert
          the file downloaded by \code{downloadGenomicSequencesFromNCBI}
          from FASTA to 2bit.
    ```

- In `\examples`: Let's try to improve the formatting of the call to `forgeBSgenomeDataPkgFromNCBI()`. One option would be:
    ```
    forgeBSgenomeDataPkgFromNCBI("GCA_009729545.1",
                                 "Acidianus infernus",
                                 "ASM972954v1",
                                 "Jane Doe <janedoe@gmail.com>")
    ```
  However in this case, it would probably help clarify what each argument is about by naming them:
    ```
    forgeBSgenomeDataPkgFromNCBI(
        assembly_accession="GCA_009729545.1",
        organism="Acidianus infernus",
        genome="ASM972954v1",
        pkg_maintainer="Jane Doe <janedoe@gmail.com>")
    ```
  I think this adds a lot of clarity, don't you agree?

As I said, we're almost there. Hopefully I can merge this soon. Thanks again for your hard work on this.

**Comment by kakopo** [comment]
Hi @hpages!

> What about using basename() to extract the name of the 2bit file as suggested earlier? (see my previous comment above about this). Hardcoding the exact name of the 2bit file inside the function introduces a repetition: this name is already hardcoded in the body of the forgeBSgenomeDataPkgFromNCBI function. So the same knowledge is coded in two different places. This means that, if for whatever reason this name needs to be changed in the future, then it will need to be changed in two places. Not ideal! (This is the DRY principle again.)
This can easily be avoided by using basename() to make .move_seq_file() agnostic about the exact name of the file to move.

I apologize! I hadn't fully understood how to use `basename` and because of this my attempts to use it did not work. I forgot to ask for some help/clarification, but this helped me understand how to use it. Thank you.

> The function has its arguments in a very counter-intuitive order. This is very likely to confuse and mislead whoever will try to understand and/or maintain your code.

I don't fully understand what this means, unfortunately, and would appreciate a small explanation as well. I'm not sure if what I've changed in the code covers this.

I've also incorporated the man page changes. 

> However in this case, it would probably help clarify what each argument is about by naming them:
> 
> ```
> forgeBSgenomeDataPkgFromNCBI(
>     assembly_accession="GCA_009729545.1",
>     organism="Acidianus infernus",
>     genome="ASM972954v1",
>     pkg_maintainer="Jane Doe <janedoe@gmail.com>")
> ```
> 
> I think this adds a lot of clarity, don't you agree

I agree this adds more clarity, but I wonder if this would work as well (I suppose I am used to this type of formatting now!)
```
forgeBSgenomeDataPkgFromNCBI(assembly_accession="GCA_009729545.1",
                             organism="Acidianus infernus",
                             genome="ASM972954v1",
                             pkg_maintainer="Jane Doe <janedoe@gmail.com>")
```

**Comment by kakopo** [comment]
I'm not sure what exactly I may have changed, as running the function now returns this warning:
```
Warning message:
In file.rename(from = twobitfile, to = file.path(new_dir, basename(twobitfile))) :
  cannot rename file './BSgenome.Ainfernus.NCBI.ASM972954v1' to '/tmp/RtmpsadxBP/single_sequences.2bit/inst/extdata/BSgenome.Ainfernus.NCBI.ASM972954v1', reason 'Not a directory'
```
and does not move the file at all. I have tried debugging and noticed that throughout most of the function, `pkg_dir` and `twobitfile` return expected values i.e `tmp/RtmpsadxBP/single_sequences.2bit` and `./BSgenome.Ainfernus.NCBI.ASM972954v1`, debugging `.move_seq_file` returns these `pkg_dir` as a temporary file path.

UPDATE: I have changed nothing, and running the function has no errors. I wonder if there is a particular reason the previous warning appeared. I had earlier thought it was because of the arguments but I fear this is not the case.

**Comment by vjcitn** [comment]
Hi, apropos https://github.com/Bioconductor/BSgenomeForge/pull/12#issuecomment-1385638537 I think you'll have to create the destination folder for file.rename to work.  In other words, `/tmp/RtmpsadxBP/single_sequences.2bit/inst/extdata/` would have to exist for a file to be renamed there.

**Comment by hpages** [comment]
>> The function has its arguments in a very counter-intuitive order. This is very likely to confuse and mislead whoever >will try to understand and/or maintain your code.
>
>I don't fully understand what this means, unfortunately, and would appreciate a small explanation as well. I'm not sure if what I've changed in the code covers this.

A more "natural" order for the arguments is: first the file to move, then the destination. Like in the `file.rename` and `file.copy` functions, and also in file manipulation functions from other language e.g. `os.rename`, `os.replace`, `shutil.copy`, etc... in Python, or in Unix commands `cp` and `mv`. This is kind of the universally accepted order.

Note that, strictly speaking, the current order of the `.move_seq_file()` arguments is not "wrong". It's just unexpected and confusing, so makes the code unnecessarily harder to read, understand, and maintain.

> I agree this adds more clarity, but I wonder if this would work as well (I suppose I am used to this type of formatting now!)
> ```
> forgeBSgenomeDataPkgFromNCBI(assembly_accession="GCA_009729545.1",
>                              organism="Acidianus infernus",
>                              genome="ASM972954v1",
>                              pkg_maintainer="Jane Doe <janedoe@gmail.com>")
> ```

Both are fine. The former saves horizontal space at the cost of one more line, so is a good alternative if the name of the function and arguments are too long to fit in the horizontal space. With your formatting, the command still fits in my 80-char wide terminal when I open the man page with `?forgeBSgenomeDataPkgFromNCBI`, so all is good.

Still a couple of things:
- "The" is missing at the begining of the sentence in `\description`.
- The man page should mention the fact that the value is returned invisibly (see my previous comment above).

Also I wonder what happened to the `genome` argument in the latest version of the man page?

Don't hesitate to ask if you have questions or if I need to clarify some of the points discussed earlier, thanks!

**Comment by hpages** [comment]
@vjcitn I think @kakopo had temporarily switched the order of the arguments in her _call_ to `.move_seq_file()` but without switching them in the _definition_ of the function itself (we just discussed this in our daily call).

**Comment by kakopo** [comment]
Thank you for the explanataion regarding `.move_seq_file()`. I've updated the code with the necessary changes and hope its satisfactory. Please take a look.

**Comment by hpages** [comment]
Awesome! :heavy_check_mark: :fireworks: :partying_face:

**Pull request merged**
