### PR TITLE
Implement basic functionality for fastaTo2bit()

### PR DESCRIPTION
**Pull request by kakopo**

### CODE REVIEW

**Comment by hpages** [comment]
Yes, that's it! Glad you figured it out :smiley: As you can see, it's a pretty straightforward function. A good way to approach a coding problem is to try to quickly come up with something that works. Once we have this, we can focus on the other things: argument checking, error handling, performance, handling edge cases, documentation, etc...

Also it's great that you were able to create a man page.

**A few  things about the man page**

- About the `\description`:
    ```
    This is a utility function to convert a downloaded FASTA file to 2bit format
    ```
    Even though it's true that our main use case will be to use `fastaTo2bit()` on FASTA files downloaded from NCBI, the function could be used on any FASTA file, including a FASTA file that was generated locally. In other words, where the FASTA file is coming from or how it was obtained is irrelevant from the perspective of the `fastaTo2bit()` function, so it's better to avoid suggesting that the function would only work on a FASTA file that was downloaded. All this to say that it would be better to remove "downloaded" from your sentence.
    Also a period (`.`) is needed at the end of the sentence. 

- You need a space between `e.g.` and `felCat9.fa` in `(e.g.felCat9.fa)`. Also since `origfile` is expected to be an _R string_, I would suggest that you actually show a string. So `(e.g. "felCat9.fa")`.
    Furthermore, since we are showing R code, we should wrap it inside `\code{}`, so `(e.g. \code{"felCat9.fa"})`.

- For `destfile` you wrote:
    ```
    A converted 2bit file within the specified directory.
    ```
    The "within the specified directory" part is confusing since the user is not specifying a directory. What the user must supply via the `destfile` argument is the path to the 2bit file to be written. So the man page should just say that:
    ```
    A single string containing the path to the 2bit file to be written.
    ```
    Note that you could also show an example here, like you did for `origfile`. Like this:
    ```
    A single string containing the path to the 2bit file to be written (e.g. \code{"felCat9.2bit"}).
    ```

- We should always add at least a simple working example to our man pages. Please add an `\examples` section with a very simple example that does the following:
    1. Call `downloadGenomicSequencesFromNCBI()` to download a small FASTA file from NCBI (try to find something as small as possible so the example does not waste time and bandwidth in the download). The file should be downloaded to the `tempdir()` folder.
    2. Call `fastaTo2bit()` on the downloaded file to convert it to the 2bit format. The 2bit file should also be created inside the `tempdir()` folder.

  The reason we use the `tempdir()` folder in the examples is to not pollute the user's home directory when the user runs the examples with `example(fastaTo2bit)`.

- Finally add a `\seealso` section to link your man page to:
    1. `downloadGenomicSequencesFromNCBI`'s man page
    2. `readDNAStringSet`'s man page in the **Biostrings** package
    3. `export.2bit`'s man page in the **rtracklayer** package

**Argument checking**

Now that you have a working version of the function, you could add some argument checking to it:

- For the `origfile` argument: 2 checks: (1) check that this is a single string (with `isSingleString()`) and issue an error if it's not, then (2) check that it's the path to an existing file (with `file.exists()`) and issue an error if it's not. One gotcha with `file.exists()` is that it also returns `TRUE` if the supplied path is to an existing directory. Of course it would be wrong for the user to supply such path (the supplied path should be to a file, not to a directory). Please investigate how you could extend the 2nd check to issue an error if the user does that.

- For the `destfile` argument: check that this is a single string and issue an error if it's not. Not sure what other check we could do on this argument. Try to call `fastaTo2bit()` with the same arguments twice in a row. What happens to the 2bit file that was produced by the 1st call? Are we ok with that?

All the error messages issued by the argument checking code should be as informative as possible.

Also please always use the left arrow (`<-`) instead of `=` for assignment.

Let me know if you have questions.

**Comment by hpages** [comment]
Argument checking looks good, thanks! Please use 4-space indentation increments (your `stop()` statements use 2-space indentation with respect to the previous indent level).

What happens if the user specifies the path to a directory instead of a file for `origfile`. Can you try this? How can we improve our argument checking to let them know that they are doing something wrong?

I missed this earlier (this is in the body of the `fastaTo2bit` function):
```
myfile <- readDNAStringSet(origfile)
```
How we choose to name our variables matters. It can help make our code easier to read and understand, or it can make it a little bit obscure/confusing/misleading. In this case the variable `myfile` is not a file, it's an object of class DNAStringSet. DNAStringSet objects are in-memory objects that represent a collection of DNA sequences. So the name of the variable is actually misleading. Maybe look at the `fasta_to_sorted_2bit.R` scripts for another, less misleading name?

I also missed this:
```
\usage{
fastaTo2bit <- function(origfile, destfile)
}
```
The `fastaTo2bit <- function(origfile, destfile) ...` syntax is the syntax we use to _define_ a function. However, the `\usage` section should show what a _call_ to the function looks like (remember that the man page is intended for the user). The way one is supposed to _call_ the function is `fastaTo2bit(origfile, destfile)`.

Compare this:
```
    A single string containing the path to the intended FASTA file
    to be read (e.g. \code{"felCat9.fasta"})
```
to this:
```
    A single string containing the path to the FASTA file
    to read (e.g. \code{"felCat9.fasta"})
```
Which one is clearer?

I also missed this:
```
\value{
  A converted 2bit file within the specified directory.
}
```
Does your function actually return _a value_? How can you check that? What value do you see?

About this:
```
    \item The \code{\link{readDNAStringSet}} function in the Biostrings package
          to read/write an XStringSet object from/to a file.
```
The `readDNAStringSet` function only _reads_ an XStringSet object from a file. _Writing_ an XStringSet object to a file is handled by another function.
Also the end-user doesn't know the relationship between our function (the `fastaTo2bit` function) and the `readDNAStringSet` function, because they don't necessarily know how our function is implemented. So from their point of view, it would seem that the `\seealso` section is listing random functions. To avoid this, we can clarify with something like:
```
    \item The \code{\link{readDNAStringSet}} function in the \pkg{Biostrings} package
          that \code{fastaTo2bit} uses internally to import the FASTA file.
```
Note the use of `\pkg{}` around package names (the Rd format uses a simple markup language described in the "Writing R Extensions" manual [here](https://cran.r-project.org/doc/manuals/r-release/R-exts.html), in the "2 Writing R documentation files" section).

Same problems here:
```
    \item The \code{\link{export.2bit}} function in the rtracklayer package
          to read/write an XStringSet object from/to a file.
```

The "`tempdir()` folder" is a temporary folder returned by the `tempdir()` function. See `?tempdir` for more information. So you should not use a hardcoded path like `"~/tempdir/somefile"` to access a file located in the "`tempdir()` folder". This won't work because the `"~/tempdir/"` folder doesn't exist in general. Instead, you need to construct a file path programmatically with something like `file.path(tempdir(), "somefile")`.

Finally:
> In the case of calling the `fastaTo2bit()` with the same arguments twice, the file is created by the first call is simply
> modified. As of now, this seems alright but I am going to make a closer analysis of the file and see if a check to
> prevent a second call would be necessary.

There are several common ways to handle this:
1. Do nothing and let the new file silently replace the existing file.
2. Issue a warning if replacing an existing file.
3. Raise an error with an error message asking the user to remove the existing file first.
4. Add a `replace` argument to the `fastaTo2bit()` function that is set to `FALSE` by default. If `replace=TRUE`, then silently replace the existing file. If `replace=FALSE`, then raise an error with an error message asking the user to call the function again with `replace=TRUE`. This is the most user-friendly behavior but it comes at the cost of an additional argument to the function.

Note that the `export.2bit()` function itself does 1., that is, it just silently replaces the existing file 2bit file. Maybe it's ok to do the same with `fastaTo2bit()` but I wanted to mention this because this is the typical kind of discussion/decision that arises when we design software.

As always, don't hesitate to let me know if you have questions or if I need to clarify things further. Thanks!

**Comment by hpages** [comment]
Yes, if the code in your package uses a function defined in another package, then you need to import that other package by adding it to your `NAMESPACE` file and to the `Imports` field of your `DESCRIPTION` file.

But note that we should always refrain from introducing unnecessary dependencies. I don't know where the `isDirectory()` function is defined, I've never heard of it, but it's not needed because the **base** package already has a function that does the job: `dir.exists()`. I should have given you the name of that function earlier, sorry. The reason I didn't is because I was hoping that the man page for `file.exists()` would mention it (e.g. via its "See also" section), but I realize now that it only mentions `dir.create()`. `dir.create()` and `dir.exists()` are documented in the same man page so it's still kind of possible to discover the latter from `?file.exists`, but it's not as straightforward as I would have hoped :disappointed: 

Remember that **base** is always automatically imported so we don't need to explicitely import it.

Finally there's no need to download the FASTA file twice in your example. Once is enough :wink: 

Almost there!

**Comment by kakopo** [comment]
Alright. Thank you for this comment. I came across `dir.exists()` at the same time as `isDirectory()`, and thought they could be inter-changeable :sweat_smile:. I've implemented the former to check if the specified path is a directory, and have updated the PR. Thanks!

**Comment by hpages** [comment]
Looks good. One last thing so I can merge: the order of the argument checks matters!

For example here:
```
    if (dir.exists(origfile))
        stop(wmsg("'origfile' must be path to a file, not a directory"))
    if (!isSingleString(origfile))
        stop(wmsg("'origfile' must be a single string"))
    if (!file.exists(origfile))
        stop(wmsg("'origfile' must be the path to an existing file"))
```
The first check should always be about the type of the argument, i.e. the `isSingleString` check in this case. Why? Because the other checks for this argument might not even work properly if `origfile` is not a single string. So we first want to make sure that `origfile` is a single string before we perform any other check.

For example, see what happens if the user provides an `origfile` that is a character vector of length > 1. Try it (e.g. with `fastaTo2bit(c("foo", "bar", "."), "out.2bit")`), and see what happens. As you will see, `if (dir.exists(origfile))` will raise an error.

This error is due to the fact that `dir.exists()` is _vectorized_, so when called on a vector of paths, it returns a vector of logicals of the same length as the supplied vector of paths. For example:
```
> dir.exists(c("foo", "bar", "."))
[1] FALSE FALSE  TRUE
```
This logical vector of length 3 cannot be used as the `if` condition of the `if` statement.

Here is an important thing to keep in mind: **We should always make sure that the `if` condition we put in our `if` statements is an expression that is _guaranteed_ to evaluate to a `TRUE` or `FALSE`.**

This is the reason why we want to make sure that `origfile` is a _single_ string _before_ doing `if (dir.exists(origfile)) ...`.

Please make this change so I can merge this, and we can move on to issue #7 (yesterday I created a separate issue for this improvement to `fastaTo2bit()`).

Thanks

**Comment by kakopo** [comment]
Hi @hpages. 
Thank you for explaining the importance of the order in argument checks/ I'll definitely keep this in mind as we continue. 
I have just updated the PR. Thank you!

**Pull request merged**
