### PR TITLE
downloadGenomicSequencesFromNCBI

### PR DESCRIPTION
**Pull request by Priceless-P**
I created `downloadGenomicSequencesFromNCBI.R`  and `downloadGenomicSequencesFromNCBI.Rd`files and also exported it in the `NAMESPACE` file

### CODE REVIEW

**Comment by Priceless-P** [comment]
Hi @hpages, I wanted to confirm if the default value of `quiet` for `downloadGenomicSequencesFromNCBI` should be `FALSE` as it is in the `download.file` function.

Also for the `method` parameter should it have a default value (of internal maybe?) or should users be given the option of choosing it themselves?

**Comment by hpages** [comment]
Hi @Priceless-P,

Yes, the arguments that we pass down to `download.file()` should have the same defaults as in `download.file()`.

Also about this:
```
if (is.null(assembly_accession))
{
    stop("assembly_accession is required")
}
if (is.null(assembly_name))
{
    stop("assembly_name is required")
}
```
The `assembly_accession` argument doesn't have a default value, which is fine, that's how it should be. When an argument doesn't have a default value, and the user calls the function without supplying the argument, R will raise an error. For example:
```
foo <- function(x) x*x
foo(11)
# [1] 121
foo()
# Error in foo() : argument "x" is missing, with no default
```
As you can see the error message is informative. So we don't need to write code to expressly handle that case. It's already taken care of :smiley: 

For `assembly_name` name though, we only add this argument to our function because `find_NCBI_assembly_ftp_dir()` has it. The only thing we will do with it is pass it down to `find_NCBI_assembly_ftp_dir()`, so we don't really need to know more about this argument. However, as you've probably seen, `find_NCBI_assembly_ftp_dir()` doesn't require `assembly_name`. We know this because the argument has a default value of `NA`. So we should do the same thing that we did with the arguments that we pass down to `download.file()`, that is, we should use a default value for `assembly_name` that is the same as in `find_NCBI_assembly_ftp_dir()`.

Finally note that doing `if (is.null(assembly_accession))` is not how we detect that the caller didn't supply an argument. The way to do this in R is with `missing()`:
```
foo <- function(x) { if (missing(x)) stop("argument 'x' is required"); x*x }
foo()
# Error in foo() : argument 'x' is required
```
But as I said, R already takes care of doing that for us so we shouldn't do it. (The situations where we need to use `missing()` are actually rare.)  

Hope this makes sense. Let me know if you have more questions.

**Comment by Priceless-P** [comment]
Okay @hpages . Makes total sense. I will remove those.😊

>Finally note that doing if (is.null(assembly_accession)) is not how we detect that the caller didn't supply an argument. The way to do this in R is with missing()

I kind of thought they can be used interchangably but i was wrong. `NULL` can be a value of argument. Hence why `missing(x)` is the way to go.

**Comment by hpages** [comment]
Hi @Priceless-P, were you able to make any progress on this? Are you planning to improve your PR? Let me know if you have questions. Thanks!

**Comment by Priceless-P** [comment]
Hi @hpages , I am certainly working on it. Will be ready in no time. 
Thanks for checking up on me.

**Comment by Priceless-P** [comment]
Hi @hpages, I'm stuck 😥 I think the `downloadGenomicSequencesFromNCBI()` function is okay. Do you think so too? 

But the man page is a little challenging. How do make I `example` to be like the ones in the other man pages? Like to make it runnable. 

``` Also in the example, show how to import the file in R as a DNAStringSet object```
Please can give me a hint on how to go about this?

**Comment by hpages** [comment]
Nice to see that you've added some basic argument checking to your function. Note that argument checking should be the very first thing that a function does. Then, only after the arguments have been checked should the function start doing "the real work", e.g. call `find_NCBI_assembly_ftp_dir()` etc... The reason to do things in this order is that "the real work" can take time, sometimes a very long time. OTOH argument checking is usually super fast. And it's always better to fail early than late. It could understandably be frustrating for the user to call a function, see it do a lot of work, and finally see it fail after a long time because one argument was not as expected. The user would rightly think: why didn't you tell me this earlier? :wink:

**About these 2 lines:**

    file_url <- find_NCBI_assembly_ftp_dir(assembly_accession)[[1]]
    file_name <- find_NCBI_assembly_ftp_dir(assembly_accession)[[2]]

`find_NCBI_assembly_ftp_dir()` is called twice with the same argument. The function is deterministic so the 2 calls are expected to return exactly the same thing. A general principle in software engineering is that we should try to avoid computing the same thing twice. This is usually achieved by storing intermediate results in variables.

In this case, you could simply do:

    ftp_dir <- find_NCBI_assembly_ftp_dir(...)
    ftp_dir_url <- ftp_dir[[1]]
    file_prefix <- ftp_dir[[2]]

Note that I've also tried to choose variable names that reflect the content of the variables, that is, `ftp_dir_url` for the URL to the FTP directory of the NCBI assembly, and `file_prefix` for the prefix used for all the file names in the directory. Using `file_url` and `file_name` for this would be quite misleading and slightly hurt the readability of the code.

**About the `assembly_name` argument:** Your current version of the function ignores the argument. This argument needs to be passed to the call to `find_NCBI_assembly_ftp_dir()`. The user is not required to supply it (and most of the times it's not needed), but IIRC there are some rare situations where `find_NCBI_assembly_ftp_dir()` actually needs this extra information in order to find the FTP directory for the assembly. I don't remember the details of when and why this is needed exactly, but it doesn't really matter. Let's just pass this argument down to `find_NCBI_assembly_ftp_dir()`.

**About what the function should return:** I'm just going to copy/paste what I wrote in #2 about this:

Every function in R returns a value. To be clear, the returned value is the value that gets stored in `res` when we do something like `res <- foo()`, it's not what the function displays or the file that it downloaded. These things are only _side effects_. In the case of `downloadGenomicSequencesFromNCBI()`, it would be useful to return the path to the downloaded file. To do this, just put `destfile` on the last line of the body of the function. Alternatively you could also put `return(destfile)` but using `return()` in the last line of a function's body is not required in R. It's only required when we need to return earlier. For example:

    absolute_value <- function(x) {
        if (x >= 0)
            return(x)  # return() required
        -x  # return() not required
    }

Returning the path to the downloaded file will allow the user to programmatically obtain this path with:

    filepath <- downloadGenomicSequencesFromNCBI(...)

This will be particularly useful when `downloadGenomicSequencesFromNCBI()` is used inside a higher-level function that needs to access the downloaded file in order to process it.

Note that a refinement that is often used in R in this kind of situation is to have the function return an _invisible value_. This is done by wrapping the returned value in `invisible()`, like this:

    downloadGenomicSequencesFromNCBI <- function(...)
    {
        ...
        invisible(destfile)
    }

This only makes a difference when we call the function interactively and without assigning its result to a variable, like here:

    downloadGenomicSequencesFromNCBI(...)

In this case, the returned value won't be displayed. Which is ok because in this case it doesn't really need to be displayed. This is just a minor refinement to the function, in order to reduce unnecessary verbosity (a.k.a. noise) as much as possible when the function is used interactively.

**About the examples in the man page:** There's nothing special to do to make the examples runnable. When we say that the man pages should contain _runnable_ examples, all we're are saying is that the `\examples` section should contain valid R code that the user should be able to run. Note that the examples will also be run by `R CMD check`.

To import the downloaded FASTA file in R as a DNAStringSet object, you just need to call a function that can read the file. It's a function that you've already used before in several occasions (hint: it's from the **Biostrings** package). Hope this helps.

There will be more to discuss about the man page but we'll do it when you've addressed the above points.

**Comment by Priceless-P** [comment]
Hi mentor, I have made the changes you requested. Please take a look when you can.

**Comment by hpages** [comment]
Hi @Priceless-P, do your examples work for you? They don't for me:
```
> library(BSgenomeForge)
> example(downloadGenomicSequencesFromNCBI)
Error in source(tf, local, echo = echo, prompt.echo = paste0(prompt.prefix,  : 
  /tmp/RtmpxGXr4r/Rex95c668a0e07b:11:5: unexpected symbol
10: # x <- readDNAStringSet(full_url)
11: for example
        ^
```

**Comment by Priceless-P** [comment]
@hpages , Please is this correct? I don't think, considering the fact that I'm getting this error
```
genome_sequence <- import(x)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘import’ for signature ‘"DNAStringSet", "missing", "missing"’
```
Please what am i doing wrong?

**Comment by hpages** [comment]
Hi @Priceless-P ,

Let's put the examples in your man page aside for the moment and focus on your function. The function does not work as expected in its current form. One major problem is that the downloaded file gets renamed i.e. it doesn't have the same name as the remote file.

As you figured out, the name of the remote file can be obtained with `paste0(file_prefix, "_genomic.fna.gz")`.  This is the name you form when you compute the URL to the file with:
```
full_url <- paste0(ftp_dir_url, "/", file_prefix, "_", "genomic.fna.gz")
```
One suggestion here is to proceed in 2 steps: one step to compute the file name, and one step to compute the URL to the file. Like this:
```
filename <- paste0(file_prefix, "_genomic.fna.gz")
full_url <- paste0(ftp_dir_url, "/", filename)
```
This makes the code a little bit clearer.

Now the major problem in your code is this line:
```
destfile <- file.path(".", file_prefix)
```
`destfile` will be passed to `download.file()`. It determines where the file should be downloaded. Note that `file.path(".", file_prefix)` will return a path that looks like this: `./<file_prefix>`. There are 2 problems with this:
- The first one is that the name of the downloaded file will be `file_prefix` and not `filename`.
- The second one is that the file will always be downloaded in the current directory (the `.` directory refers to the current directory). That's not what we want. The file should be downloaded to the directory specified by the user via the `destdir` argument (`.` is only the default). Right now, your code does some checking on `destdir`, which is good, but then it doesn't use it for anything. So the destination directory specified by the user gets ignored.

These problems need to be fixed. Once you've done enough testing of your function and you're confident that it works as expected, we'll discuss the man page.

Don't hesitate to let me know if you have questions and I'll do my best to clarify things.

**Comment by Priceless-P** [comment]
Hi @hpages, I have made the corrections. Is the function okay now?

**Comment by Priceless-P** [comment]
Hi @hpages, It's been a while. I hope you're doing okay.

About the example on the man page. I ran the example in the `downloadGenomicSequencesFromUCSC` And I found that

```
filepath <- downloadGenomicSequencesFromUCSC("sacCer1", destdir=tempdir())
genome_sequence <- import(filepath)
genome_sequence
```
returns
```
DNAStringSet object of length 17:
       width seq                                               names               
 [1]  230208 CCACACCACACCCACACACCCAC...GGTGTGGGTGTGGTGTGTGTGGG chr1
 [2]  745446 CCCACACACACACCACACCCACA...GGGTGTGGTGTGTGTGTGGGTGT chr10
 [3]  666445 CACCACACCCACACACCACACCC...GGGTGTGGGTGTGGTGTGTGTGT chr11
 [4] 1078173 CACACACACACACCACCCACACA...GGAGACGTACATGAGGGCTATTT chr12
 [5]  924430 CCACACACACACCACACCCACAC...GTGGGTGTGGTGTGTGTGTGGGG chr13
 ...     ... ...
[13]  270148 GATCTCGCAAGTGCATTCCTAGA...TGGTGTGTGGGTGTGGTGTGTGG chr6
[14] 1090944 CCACACCCACACACACCACACCC...GTTTCATTTTCATTTTTTTTTTT chr7
[15]  562639 CCCACACACACCACACCCACACA...GTGTGGGTGTGGTGTGTGTGTGG chr8
[16]  439885 CACACACACCACACCCACACCAC...GGATGTGGGTGTGGTGTGTGTGT chr9
[17]   85779 TTCATAATTAATTTTTTATATAT...TTAATTATAATATAATATCCATA chrM
>
```
which is similar to the output I get when I do 
```
genome_sequence <- readDNAStringSet(file_path)
genome_sequence
``` 
So I used `readDNAStringSet()` instead of `import()` since the latter doesn't seem to support `fna` files.

`R CMD build` and `R CMD check` produced no error. In a new session, I installed the package and played around with the new functionality, everything seems to be working fine. Please can check and give me feedback?

Thank you.

**Comment by hpages** [comment]
Hi @Priceless-P ,

Sorry for the slow response and thanks for your patience.

Function looks good. Make sure that it behaves as expected when you specify `destdir`. Indentation of your `if` statements need to be fixed.

For the man page:

- Something is missing before `is` at the beginning of your `\description` section:
    ```
    \description{
      is a utility function that finds and downloads
      the compressed FASTA file from NCBI, for a given assembly.
    }
    ```

- About the `assembly_accession` argument:
    ```
    \item{assembly_accession}{
      A single string containing a GenBank assembly accession (e.g.          "GCA_000001405.15"),
      a RefSeq assembly accession (e.g. "GCF_000001405.26"), or an NCBI assembly name (e.g. "GRCh38").
    }
    ```
  Unfortunately using an NCBI assembly name (e.g. `"GRCh38"`) doesn't work (you can try). But I can see that the confusion comes from the documentation of the `assembly_accession` argument in the man page for the `find_NCBI_assembly_ftp_dir` function in the **GenomeInfoDb** package. My bad. This is now corrected in **GenomeInfoDb** 1.35.5.
  Also please reformat the above so it fits in lines of 80 chars max.

- About this:
    ```
    \item{destdir}{
      A 'character' string indicating the path where
      the downloaded file is to be stored.
      It is set to \code{"."} by default.
      See the BSgenomeForge vignette in this package for more information.
    }
    ```
  Note that the BSgenomeForge vignette is not in this package (it's in the **BSgenome** package). But more importantly, I don't think we should mention this vignette here. The vignette documents the old way of forging a BSgenome data package. OTOH the `downloadGenomicSequencesFromNCBI` function will be part of the **BSgenomeForge** _package_, a new package that will provide a new set of tools for forging a BSgenome data package the new way. Those tools will supersede the old BSgenomeForge vignette, so it's better to not refer to the latter in the documentation of the former.

- Why the `library("GenomeInfoDb")` statement? The examples are not calling any function from that package.

- Use a colon (`:`) at the end of your last comment in the examples, like you did for all your other comments.

Note that you created a PR from a branch that has conflicts so I won't be able to merge it. I'm not sure what's the best way to deal with this. I think you can try to: (1) resync your fork, then (2) merge the master branch into your downloadGenomicSequence branch. Hopefully you'll manage to do this.

Thanks

**Comment by Priceless-P** [comment]
Hi @hpages,

I have made the specified corrections.

>Make sure that it behaves as expected when you specify destdir

Yes It works as expected.

**Comment by Priceless-P** [comment]
I have updated it now @hpages

**Pull request merged**
